trigger:
- master

pool: my local machine

jobs:
- job: Build
  displayName: 'Build and Push Docker Image'
  steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerACRServiceConnection'  # Use the exact name of your Docker Registry service connection
        repository: 'assignment1files-server'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          latest

- job: Deploy
  displayName: 'Deploy to Azure App Service'
  dependsOn: Build
  steps:
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'AzureResourceConnection'  # Your Azure subscription service connection name
        appName: 'ASP-Todoappgroup-acde'
        imageName: 'joeljoselabfordevops.azurecr.io/assignment1files-server:latest'
