trigger:
- master  # Triggers the pipeline on push to the master branch

pool:
  vmImage: 'ubuntu-latest'  # Using Ubuntu for the pipeline jobs

jobs:
- job: Build
  displayName: 'Build and Push Docker Image'
  steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'ACRServiceConnection'  # ACR service connection name
        repository: 'assignment1files-server'  # Docker repository in ACR
        command: 'buildAndPush'  # Builds and pushes the Docker image to ACR
        Dockerfile: '**/Dockerfile'  # Path to your Dockerfile
        tags: |
          latest

- job: Deploy
  displayName: 'Deploy to Azure App Service'
  dependsOn: Build
  steps:
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'AzureResourceConnection'  # Azure service connection name
        appName: 'ASP-Todoappgroup-acde'  # Your Azure App Service name
        imageName: 'joeljoselabfordevops.azurecr.io/assignment1files-server:latest'  # ACR image reference
        containerCommand: ''  # Optional command to run inside the container
