# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
  containers:
    - container: JoelJoselabfordevops
      image: 'joeljoselabfordevops.azurecr.io/assignment1files-server:latest'

jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'JoelJoselabfordevops'  # Your ACR service connection name
          repository: 'assignment1files-server'
          command: 'buildAndPush'
          dockerfile: '**/Dockerfile'
          tags: |
            latest

  - job: Deploy
    dependsOn: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: AzureWebApp@1
        inputs:
          azureSubscription: 'Azure for Students'  # Your Azure subscription name
          appName: 'ASP-Todoappgroup-acde'  # Name of your Azure App Service
          containerRegistry: 'JoelJoselabfordevops'  # Your ACR service connection name
          imageName: 'joeljoselabfordevops.azurecr.io/assignment1files-server:latest'